apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: order-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: order
      template:
        metadata:
          labels:
            app: order
        spec:
          containers:
            - name: order
              image: order:wk5
              ports:
                - containerPort: 5001
              imagePullPolicy: Never # or Never

  - apiVersion: v1
    kind: Service
    metadata:
      name: order-service
    spec:
      selector:
        app: order
      ports:
        - protocol: TCP
          port: 5001
          targetPort: 5001
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: shipping-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: shipping
      template:
        metadata:
          labels:
            app: shipping
        spec:
          containers:
            - name: shipping
              image: shipping:wk5
              ports:
                - containerPort: 5002
              imagePullPolicy: Never # or Never

  - apiVersion: v1
    kind: Service
    metadata:
      name: shipping-service
    spec:
      selector:
        app: shipping
      ports:
        - protocol: TCP
          port: 5002
          targetPort: 5002
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: activity-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: activity
      template:
        metadata:
          labels:
            app: activity
        spec:
          containers:
            - name: activity
              image: activity:wk5
              ports:
                - containerPort: 5003
              imagePullPolicy: Never # or Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: activity-service
    spec:
      selector:
        app: activity
      ports:
        - protocol: TCP
          port: 5003
          targetPort: 5003
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: error-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: error
      template:
        metadata:
          labels:
            app: error
        spec:
          containers:
            - name: error
              image: error:wk5
              ports:
                - containerPort: 5004
              imagePullPolicy: Never # or Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: error-service
    spec:
      selector:
        app: error
      ports:
        - protocol: TCP
          port: 5004
          targetPort: 5004
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: placeorder-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: placeorder
      template:
        metadata:
          labels:
            app: placeorder
        spec:
          containers:
            - name: placeorder
              image: placeorder:wk5
              ports:
                - containerPort: 5100
              imagePullPolicy: Never # or Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: placeorder-service
    spec:
      selector:
        app: placeorder
      ports:
        - protocol: TCP
          port: 5100
          targetPort: 5100
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: db-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: db
      template:
        metadata:
          labels:
            app: db
        spec:
          containers:
            - name: db
              image: db
              env:
                - name: MYSQL_ROOT_PASSWORD
                  value: root
                - name: MYSQL_DATABASE
                  value: order
              ports:
                - containerPort: 3306
              volumeMounts:
                - mountPath: /var/lib/mysql
                  name: db-storage
          volumes:
            - name: db-storage
              persistentVolumeClaim:
                claimName: db-pvc
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: db-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: Service
    metadata:
      name: db-service
    spec:
      selector:
        app: db
      ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rabbitmq-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: rabbitmq
      template:
        metadata:
          labels:
            app: rabbitmq
        spec:
          containers:
            - name: rabbitmq
              image: "rabbitmq:3-management"
              ports:
                - containerPort: 5672
                - containerPort: 15672
  - apiVersion: v1
    kind: Service
    metadata:
      name: rabbitmq-service
    spec:
      selector:
        app: rabbitmq
      ports:
        - name: amqp
          protocol: TCP
          port: 5672
          targetPort: 5672
        - name: management
          protocol: TCP
          port: 15672
          targetPort: 15672
